before_script:
  - echo "before script"
  # let users can modify its own files. git object files are 444 (read-only for everyone.)
  - chmod u+w -R .git/
  - pip3 install --user ./

after_script:
  - echo "after script"
  - pip3 uninstall -y pegaflow

stages:
  - test

test_workflow:
  stage: test
  script:
    - echo "Generate and submit the workflow ... "
    - pwd
    - cd pegaflow/example/
    - ./WordCountFiles.py -i /y/home/huangyu/script/test/python/ --inputSuffixList .py -l condor -o wc.python.code.xml -C 10
    - ./submit.sh ./wc.python.code.xml condor
    - pegasus-status work/wc.python.code.*
    - ../test/run_til_workflow_end.sh work/wc.python.code.*/jobstate.log
    - pegasus-status work/wc.python.code.*
    - mv wc.python.code.*/merged.txt ./
  artifacts:
    name: "${CI_BUILD_ID}_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 3 mos
    paths:
    - pegaflow/example/merged.txt

