before_script:
  - echo "before script"
  # let users can modify its own files. git object files are 444 (read-only for everyone.)
  - chmod u+w -R .git/
  - pwd

after_script:
  - echo "after script"


stages:
  - install
  - check_version
  - test
  - uninstall

install:
  stage: install
  script:
    - pip3 install --user ./

uninstall:
  stage: uninstall
  script:
    - pip3 uninstall -y pegaflow

check_version:
  stage: check_version
  script:
    - echo "Checking the installed version"
    - python3 -c "import pegaflow; print(pegaflow.version)"

test_OO:
  stage: test
  script:
    - echo "Generate and run the OO-example workflow ... "
    - cd pegaflow/example/
    - ./WordCountFiles.py -i /y/home/huangyu/script/test/python/ --inputSuffixList .py -l condor -o wc.python.code.xml -C 10
    - ./submit.sh ./wc.python.code.xml condor
    - sleep 5 && pegasus-status work/wc.python.code.*
    - ../test/run_til_workflow_end.py -j work/wc.python.code.*/jobstate.log
    - pegasus-status work/wc.python.code.*
    - mv wc.python.code.*/merged.txt ./
  artifacts:
    name: "${CI_BUILD_ID}_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 3 mos
    paths:
    - pegaflow/example/merged.txt


test_function:
  stage: test
  script:
    - echo "Generate and run the function-example workflow ... "
    - cd pegaflow/example/
    - ./WCFiles_Function.py -i /y/home/huangyu/script/test/python/ --inputSuffixList .py -l condor -o wc.python.code.xml -C 10
    - ./submit.sh ./wc.python.code.xml condor
    - sleep 5 && pegasus-status work/wc.python.code.*
    - ../test/run_til_workflow_end.py -j work/wc.python.code.*/jobstate.log
    - pegasus-status work/wc.python.code.*
    - mv wc.python.code.*/merged.txt ./
  artifacts:
    name: "${CI_BUILD_ID}_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 3 mos
    paths:
    - pegaflow/example/merged.txt

test_local:
  stage: test
  script:
    - echo "Generate and run the workflow locally ... "
    - cd pegaflow/example/
    - echo "Force shell execution. No condor required."
    - echo "pegasus.code.generator = Shell" >> pegasusrc
    - ./WordCountFiles.py -i /y/home/huangyu/script/test/python/ --inputSuffixList .py -l local -o wc.python.code.xml -C 1
    - ./submit.sh ./wc.python.code.xml local
    - pegasus-status work/wc.python.code.*
    - mv wc.python.code.*/merged.txt ./
  artifacts:
    name: "${CI_BUILD_ID}_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 3 mos
    paths:
    - pegaflow/example/merged.txt