before_script:
  - echo "before script"
  - pip3 install -e ./

after_script:
  - echo "after script"
  - pip3 uninstall -y pegaflow

stages:
  - test

test_workflow:
  stage: test
  script:
    - echo "Generate and submit the workflow ... "
    - pwd
    - cd pegaflow/example/
    - ./WordCountFiles.py -i /y/home/huangyu/script/test/python/ --inputSuffixList .py -l condor -o wc.python.code.xml -C 10
    - ./submit.sh ./wc.python.code.xml condor
    - pegasus-status work/wc.python.code.*
    # the workflow should finish within 3 minutes.
    - sleep 3m
    - pegasus-status work/wc.python.code.*
    - grep DAGMAN_FINISHED work/wc.python.code.*/jobstate.log
    - mv wc.python.code.*/merged.txt ./
  artifacts:
    name: "${CI_BUILD_ID}_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 3 mos
    paths:
    - pegaflow/example/merged.txt

